import assert from 'node:assert/strict';
import { test } from 'node:test';

import { computeProgress, milestoneKey } from './progress.ts';

test('an empty roadmap reports zero rather than NaN', () => {
  const p = computeProgress(null);
  assert.deepEqual(p, { completed: 0, total: 0, ratio: 0, next: null });
});

test('stages with no milestones do not divide by zero', () => {
  const p = computeProgress({ stages: [{ name: 'beginner', milestones: [] }] });
  assert.equal(p.total, 0);
  assert.equal(p.ratio, 0);
  assert.ok(!Number.isNaN(p.ratio), 'ratio must never be NaN');
});

test('counts across every stage, not just the current one', () => {
  const p = computeProgress({
    stages: [
      { name: 'beginner', milestones: [{ title: 'a', completed: true }, { title: 'b', completed: true }] },
      { name: 'intermediate', milestones: [{ title: 'c', completed: true }, { title: 'd', completed: false }] },
      { name: 'advanced', milestones: [{ title: 'e', completed: false }] },
    ],
  });
  assert.equal(p.completed, 3);
  assert.equal(p.total, 5);
  assert.equal(p.ratio, 3 / 5);
});

test('next is the first incomplete milestone in stage order', () => {
  const p = computeProgress({
    stages: [
      { name: 'beginner', milestones: [{ title: 'done one', completed: true }] },
      { name: 'intermediate', milestones: [{ title: 'the one', completed: false }, { title: 'later', completed: false }] },
    ],
  });
  assert.equal(p.next?.milestone.title, 'the one');
  assert.equal(p.next?.stage.name, 'intermediate');
});

test('next is null when everything is complete', () => {
  const p = computeProgress({
    stages: [{ name: 'beginner', milestones: [{ title: 'a', completed: true }] }],
  });
  assert.equal(p.next, null);
  assert.equal(p.ratio, 1);
});

test('a later completed milestone does not hide an earlier incomplete one', () => {
  // Order matters: progress should point at the earliest gap, not merely the
  // first one encountered after a completed run.
  const p = computeProgress({
    stages: [
      {
        name: 'beginner',
        milestones: [
          { title: 'first', completed: false },
          { title: 'second', completed: true },
        ],
      },
    ],
  });
  assert.equal(p.next?.milestone.title, 'first');
  assert.equal(p.completed, 1);
});

test('a stage missing its milestones array is tolerated', () => {
  // Roadmaps generated by an older prompt have been seen without `milestones`.
  const p = computeProgress({
    stages: [
      { name: 'beginner' },
      { name: 'intermediate', milestones: [{ title: 'x', completed: false }] },
    ],
  });
  assert.equal(p.total, 1);
  assert.equal(p.next?.milestone.title, 'x');
});

test('milestoneKey prefers the Mongo id', () => {
  assert.equal(milestoneKey({ _id: 'abc123', title: 'Some title' }), 'abc123');
});

test('milestoneKey falls back to the title when there is no id', () => {
  // Otherwise the completion control would address nothing and silently no-op.
  assert.equal(milestoneKey({ title: 'No id here' }), 'No id here');
});
